# Generated by Django 5.0.7 on 2024-07-23 11:23

import api.utils
import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organisation', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserOrganisation',
            fields=[
                ('id', models.CharField(default=api.utils.gen_uuid_str, max_length=60, primary_key=True, serialize=False)),
                ('created_at', models.DateField(default=datetime.datetime.now)),
                ('updated_at', models.DateField(default=datetime.datetime.now)),
                ('role', models.CharField(choices=[('owner', 'Owner'), ('member', 'Member')], default='owner', max_length=60)),
                ('organisation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='organisation.organisation')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'user_organisations',
                'unique_together': {('user', 'organisation')},
            },
        ),
    ]
