# Generated by Django 5.0.7 on 2024-07-23 11:45

import user_organisation.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_organisation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorganisation',
            name='role',
            field=models.CharField(choices=[(user_organisation.models.Roles['MEMBER'], 'MEMBER'), (user_organisation.models.Roles['OWNER'], 'OWNER')], default=user_organisation.models.Roles['OWNER'], max_length=25),
        ),
    ]
