# Generated by Django 5.0.7 on 2024-07-23 11:23

import api.utils
import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.CharField(auto_created=True, default=api.utils.gen_uuid_str, max_length=60, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(max_length=1000)),
                ('owner_email', models.EmailField(max_length=60)),
                ('created_at', models.DateField(default=datetime.datetime.now)),
                ('updated_at', models.DateField(default=datetime.datetime.now)),
            ],
            options={
                'db_table': 'organisations',
            },
        ),
    ]
