# Generated by Django 3.2.12 on 2024-07-08 23:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Organisation',
            fields=[
                ('id', models.CharField(auto_created=True, default='0849f2a1-a46c-4b44-9282-e232a4ec75cc', max_length=60, primary_key=True, serialize=False, unique=True)),
                ('name', models.CharField(max_length=60)),
                ('description', models.TextField(max_length=1000)),
                ('owner_email', models.CharField(max_length=60)),
                ('create_at', models.DateField(default=django.utils.timezone.now)),
                ('update_at', models.DateField(default=django.utils.timezone.now)),
            ],
            options={
                'db_table': 'organisations',
            },
        ),
    ]
