# Generated by Django 3.2.12 on 2024-07-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='id',
            field=models.CharField(auto_created=True, default='09a4df67-ee1d-45fa-845e-30e9d9780dcf', max_length=60, primary_key=True, serialize=False, unique=True),
        ),
    ]
