# Generated by Django 3.2.12 on 2024-07-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organisation', '0002_alter_organisation_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='organisation',
            name='id',
            field=models.CharField(auto_created=True, default='e9f34499-9fc1-4db2-8cd8-7ca0c9abe18d', max_length=60, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='owner_email',
            field=models.EmailField(max_length=60),
        ),
    ]
