# Generated by Django 3.2.12 on 2024-07-10 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user_organisation', '0003_alter_userorganisation_user_org_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userorganisation',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='userorganisation',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
