# Generated by Django 3.2.12 on 2024-07-10 00:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_organisation', '0004_auto_20240710_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userorganisation',
            name='created_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='userorganisation',
            name='updated_at',
            field=models.DateField(default=datetime.datetime.now),
        ),
    ]
