# Generated by Django 3.2.12 on 2024-07-08 22:50

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.CharField(auto_created=True, default='f0b0071f-cbf8-407a-986f-4f269ffbb8bd', max_length=60, primary_key=True, serialize=False, unique=True)),
                ('firstName', models.CharField(max_length=60)),
                ('lastName', models.CharField(max_length=60)),
                ('email', models.CharField(max_length=60, unique=True)),
                ('password', models.CharField(max_length=60)),
                ('phone', models.CharField(max_length=15)),
                ('create_at', models.DateField(default=datetime.datetime(2024, 7, 8, 22, 50, 27, 554207, tzinfo=utc))),
                ('update_at', models.DateField(default=datetime.datetime(2024, 7, 8, 22, 50, 27, 554246, tzinfo=utc))),
            ],
            options={
                'db_table': 'users',
            },
        ),
    ]
