# Generated by Django 3.2.12 on 2024-07-08 22:51

import datetime
from django.db import migrations, models
from datetime import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='create_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 8, 22, 51, 9, 732192, tzinfo=timezone.utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(auto_created=True, default='9047d61e-81e3-4816-a1af-8b5c17e97864', max_length=60, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_at',
            field=models.DateField(default=datetime.datetime(2024, 7, 8, 22, 51, 9, 732237, tzinfo=timezone.utc)),
        ),
    ]
