# Generated by Django 3.2.12 on 2024-07-08 22:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20240708_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='create_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(auto_created=True, default='9d4dec53-fbca-4db9-89a1-a889ef539063', max_length=60, primary_key=True, serialize=False, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='update_at',
            field=models.DateField(default=django.utils.timezone.now),
        ),
    ]
