# Generated by Django 3.2.12 on 2024-07-08 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_auto_20240708_2251'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(auto_created=True, default='5216d44f-4191-4c15-8793-d682d2a6ef92', max_length=60, primary_key=True, serialize=False, unique=True),
        ),
    ]
