# Generated by Django 3.2.12 on 2024-07-08 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(auto_created=True, default='8c0af51f-c9e1-4774-8a7e-eb1babc47c12', max_length=60, primary_key=True, serialize=False, unique=True),
        ),
    ]
