# Generated by Django 3.2.12 on 2024-07-08 22:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(auto_created=True, default='69169d7c-e2cb-4c59-9a9c-293a0d17454d', max_length=60, primary_key=True, serialize=False, unique=True),
        ),
    ]
