# Generated by Django 3.2.12 on 2024-07-08 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(auto_created=True, default='1ad79a68-86e5-4740-bc07-c91a7a9aacb4', max_length=60, primary_key=True, serialize=False, unique=True),
        ),
    ]
