# Generated by Django 3.2.12 on 2024-07-08 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(auto_created=True, default='2f039d95-6662-4aa8-868a-600e27724d94', max_length=60, primary_key=True, serialize=False, unique=True),
        ),
    ]
