# Generated by Django 3.2.12 on 2024-07-08 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(auto_created=True, default='caff8c58-b8bf-4484-be42-4aa778149761', max_length=60, primary_key=True, serialize=False, unique=True),
        ),
    ]
