# Generated by Django 3.2.12 on 2024-07-09 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(auto_created=True, default='d8a228ff-fa72-4caf-a0a4-476188db764f', max_length=60, primary_key=True, serialize=False, unique=True),
        ),
    ]
