# Generated by Django 3.2.12 on 2024-07-09 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.CharField(auto_created=True, default='<function uuid4 at 0x7fe9f7e52c20>', max_length=60, primary_key=True, serialize=False, unique=True),
        ),
    ]
