# Generated by Django 3.2.12 on 2024-07-09 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_user_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='create_at',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='update_at',
            new_name='updated_at',
        ),
    ]
