# Generated by Django 5.0.7 on 2024-07-11 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0020_user_date_joined_user_first_name_user_groups_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
