# Generated by Django 5.0.7 on 2024-07-11 19:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0021_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
