# Generated by Django 5.0.7 on 2024-07-11 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0022_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
