# Generated by Django 5.0.7 on 2024-07-11 20:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0023_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user',
            table='users',
        ),
    ]
