# Generated by Django 5.0.7 on 2024-07-11 20:22

import api.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0025_alter_user_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(auto_created=True, default=api.utils.gen_uuid_str, max_length=80, unique=True),
        ),
    ]
